# Generated by Django 4.2.3 on 2023-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Eeitorial',
            new_name='editorial',
        ),
        migrations.RemoveField(
            model_name='bibliotecario',
            name='id_bibliotecario',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='id_lector',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigo_material',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_pedido',
        ),
        migrations.AddField(
            model_name='bibliotecario',
            name='contacto',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
